title: Preview Generator
email: donczyk.remigiusz@gmail.com
description: >-
  Create a palette preview image by using simple declarations
url: https://aonodensetsu.github.io
baseurl: prev_gen
github_username:  aonodensetsu

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

show_downloads: false

